FROM ubuntu:22.04
LABEL mantainer=fams@linuxplace.com.br
WORKDIR  /src
COPY main.go /src
COPY go.mod /src
RUN apt update -y 
RUN apt install --no-install-recommends -y golang-go
RUN go build -o httpserver main.go
RUN cp httpserver /usr/local/sbin
ENV PATH=$PATH:/usr/local/bin
COPY ./www/ /var/www/html
WORKDIR  /var/www/html
EXPOSE 80
ENTRYPOINT [ "httpserver", "-port", "80" ]
