CREATE DATABASE IF NOT EXISTS guess_game;
USE guess_game;

CREATE TABLE IF NOT EXISTS jogos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL,
    Segredo VARCHAR(50) NOT NULL,
    tentativas INT NOT NULL
);
